select *from PULPIT;
select *from TEACHER;
SELECT *FROM FACULTY;
SELECT *FROM STUDENT;

SELECT *FROM TEACHER AT FULL OUTER JOIN FACULTY AA
ON AA.TEACHER_NAME = at.FACULTY_NAME
ORDER BY AA.TEACHER_NAME, at.FACULTY_NAME
