use UNIVER1
select *from FACULTY;
select *from PROGRESS;
select *from GROUPS;
select *from STUDENT;


--1
SELECT 
AUDITORIUM_TYPE.AUDITORIUM_TYPE[Тип аудитории],
max(AUDITORIUM_CAPACITY)[Максимальная вместимость],
min(AUDITORIUM_CAPACITY)[Минимальная вместимость],
avg(AUDITORIUM_CAPACITY)[Средняя вместимость],
sum(AUDITORIUM_CAPACITY)[Суммарная вместимость],
count(AUDITORIUM.AUDITORIUM_TYPE)[Общее кол аудиторий данного типа]
From 
AUDITORIUM 
Inner Join
AUDITORIUM_TYPE
On AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
GROUP BY 
AUDITORIUM_TYPE.AUDITORIUM_TYPE 


--2
SELECT *
FROM (select Case when NOTE between 4 and 6  then  'Оценка меньше 6'
when NOTE between 6 and 8 then 'Оценка от 6 до 8'
else 'Оценка больше 8'
end [Самые высокие оценки],count(*)[Количество]
From PROGRESS Group by Case
when NOTE  between 4 and 6  then  'Оценка меньше 6'
when NOTE  between 6 and 8  then  'Оценка от 6 до 8'
else 'Оценка больше 8'
end) as T
ORDER BY Case[Самые высокие оценки] 
when 'Оценка больше 8' then 1
when 'Оценка от 6 до 8' then 2
when 'Оценка меньше 6' then 3
 else 0
 end desc

--3
SELECT
    FACULTY.FACULTY,
    GROUPS.FACULTY,
    STUDENT.IDSTUDENT,
    ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS AVERAGE_GRADE
FROM
    FACULTY
INNER JOIN
    GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
INNER JOIN
    STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
INNER JOIN
    PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
GROUP BY
 FACULTY.FACULTY,
    GROUPS.FACULTY,
    STUDENT.IDSTUDENT
ORDER BY
    AVERAGE_GRADE DESC;
---4
SELECT
    FACULTY.FACULTY,
    GROUPS.FACULTY,
    STUDENT.IDSTUDENT,
	PROGRESS.SUBJECT,
    ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS AVERAGE_GRADE
FROM
    FACULTY
INNER JOIN
    GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
INNER JOIN
    STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
INNER JOIN
    PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	WHERE PROGRESS.SUBJECT   IN ('ОАиП' , 'СУБД')

GROUP BY
 FACULTY.FACULTY,
    GROUPS.FACULTY,
    STUDENT.IDSTUDENT,
	PROGRESS.SUBJECT
ORDER BY
    AVERAGE_GRADE DESC;

--5
	SELECT
    FACULTY.FACULTY,
    GROUPS.FACULTY,
    STUDENT.IDSTUDENT,
	
    ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS AVERAGE_GRADE
FROM
    FACULTY
INNER JOIN
    GROUPS ON FACULTY.FACULTY = GROUPS.FACULTY
INNER JOIN
    STUDENT ON GROUPS.IDGROUP = STUDENT.IDGROUP
INNER JOIN
    PROGRESS ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
	WHERE FACULTY.FACULTY = 'ТОВ'

GROUP BY
 FACULTY.FACULTY,
    GROUPS.FACULTY,
    STUDENT.IDSTUDENT
	
ORDER BY
    AVERAGE_GRADE DESC;

SELECT
    SUBJECT,
    COUNT(*) AS STUDENT_COUNT
FROM
    PROGRESS
WHERE
    NOTE IN (8, 9)
GROUP BY
    SUBJECT
HAVING
    COUNT(*) > 0
ORDER BY
    STUDENT_COUNT DESC;
