select *from AUDITORIUM;
select *from AUDITORIUM_TYPE;
select AUDITORIUM_TYPE.AUDITORIUM_TYPENAME,AUDITORIUM.AUDITORIUM
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
on AUDITORIUM_TYPE.AUDITORIUM_TYPENAME  = AUDITORIUM.AUDITORIUM and AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%компьютер%'

