

SELECT FACULTY.FACULTY_NAME,PULPIT.PULPIT_NAME,PROFESSION.PROFESSION_NAME,SUBJECT.SUBJECT_NAME,STUDENT.NAME,PROGRESS.NOTE,
CASE
WHEN (PROGRESS.NOTE BETWEEN 6 AND 8) THEN 'нр 6 дн 8'
ELSE 'анкэье'
END PREDEL
FROM PROGRESS INNER JOIN STUDENT
ON PROGRESS.NOTE = STUDENT.NAME
ORDER BY PROGRESS.NOTE DESC


