USE UNIVER1;
SELECT *FROM AUDITORIUM;
SELECT *FROM AUDITORIUM_TYPE;
SELECT *FROM PROGRESS;
SELECT *FROM PULPIT;
SELECT *FROM FACULTY;
SELECT *FROM GROUPS;
SELECT *FROM PROFESSION;
SELECT *FROM STUDENT;
SELECT *FROM SUBJECT;
SELECT *FROM TEACHER;
SELECT *FROM TIMETABLE;
--1
CREATE VIEW [Преподаватель] 
AS SELECT TEACHER.TEACHER [КОД],
TEACHER.TEACHER_NAME [ИМЯ],
TEACHER.GENDER[ПОЛ],
TEACHER.PULPIT[КОД КАФЕДРЫ] FROM
TEACHER
 
 SELECT *FROM [Преподаватель]
  
--2
CREATE VIEW [Количество кафедр]
as select FACULTY.FACULTY_NAME [ФАКУЛЬТЕТ],(SELECT COUNT(*) FROM PULPIT WHERE FACULTY.FACULTY=PULPIT.FACULTY) [Количество кафедр]
FROM  FACULTY
ALTER VIEW  [Количество кафедр]
as select 
FACULTY.FACULTY_NAME[Факультет],count(PULPIT.PULPIT_NAME)[Количество кафедр]
from FACULTY JOIN PULPIT ON PULPIT.FACULTY = FACULTY.FACULTY
GROUP BY FACULTY.FACULTY_NAME

SELECT *FROM [Количество кафедр]

--3

CREATE VIEW [АУДИТОРИИ] (НАИМЕНОВАНИЕ_АУДИТОРИИ,КОД) 
as select  AUDITORIUM_TYPE[НАИМЕНОВАНИЕ_АУДИТОРИИ],
AUDITORIUM.AUDITORIUM[КОД]
FROM AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM_TYPE = 'ЛК';
GO 
SELECT *FROM [АУДИТОРИИ]
INSERT [АУДИТОРИИ] VALUES ('ЛК',207-4)


--4
CREATE VIEW [Дисциплины]
as select 